# Copyright (c) 2025 BytevalKit-LLM Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEFAULT:
  task_name: demo_cot
  need_judge: true
  need_calculate: true
  need_cot_judge: true
  vllm_cfg:
    max_seq_len: 16384
  work_dir: output
DATASET:
  dataset_rewrite_asr_transcription:
    name: dataset_rewrite_asr_transcription
    question_key: instruction
    answer_key: output
    path: demo/dataset/test_data_makeup_knowledge.jsonl
MODEL:
  model_Qwen3-0.6B-Instruct:
    name: Qwen3-0.6B-Instruct
    batch_padding: false
    batch_size: 1
    max_out_len: 2048
    max_seq_len: 16384
    is_think_model: true
    cot_process_string: <think>(?P<think>.*?)</think>(?P<answer>.*)
    model_kwargs:
      torch_dtype: bfloat16
      trust_remote_code: true
    meta_template:
      SYSTEM_begin: '<|im_start|>system

        You are a helpful assistant<|im_end|>

        '
      HUMAN_begin: '<|im_start|>user

        '
      HUMAN_end: '<|im_end|>

        '
      BOT_begin: '<|im_start|>assistant

        '
      BOT_end: '<|im_end|>

        '
    path: your_path_to/Qwen3-0.6B
    run_cfg:
      num_gpus: 1
      num_procs: 1
    tokenizer_kwargs:
      padding_side: left
      return_tensors: pt
      truncation_side: left
      trust_remote_code: true
      use_fast: false
